### ISSUE TITLE
Changes requested by Florent

### ISSUE THREAD

**Issue by mithro** [litex-hub/pythondata-auto#1]
As these modules are not actually LiteX specific, we should rename packages to `pythondata-<type>-<name>`. IE `pythondata-cpu-lm32`. Then the module can be provided as `cpu_lm32`.

This also removes a lot of the empty directories and removes the need to worry about namespace packages.

We should still provide a `get_data(<type>, <name>)` style function (but that might be part of LiteX).

**Comment by enjoy-digital** [comment]
This has been done.
